language: c
sudo: false

env:
  global:
    - RACKET_DIR=~/racket
    - secure: PHNSq63ma4oMmV22OaNaocQLHk9ELna0LEQk9xU2MNrRuJm3NhSA7pTZ3kGqxcCCRUbzXtT0p/tzxkpjBWPq3AOHUaqxqbiaUnWHNfbhVPhWoxmMlh811bR6HnVv8qnGrDH21gJtkzySg45y8YWZaP8Zq3559eVVcTlgK3XM7/xPuJkl5aG+sqqZzgLTaHlB0TS4+acSfjjhEt+71lm6OOqz7P8/VEunhptB1fphP8knKcDCXMZV85csuq8uxmqRpbQWGTANc7+gTi9zt8mZ914ZFvLqH3Aja3RIK+N/vBmM/PsTmTGEzCJ5obwhFXc9c+q8Aln2dddQ2d2E0UrmxjYP9SBNTL5sc2IgavxYBmnYW5hq/F9ZFDeUWo4DKjspeJYagku9s69PK6qQ/N99y8sPq4Aza3GOxayDePU4cyM8DjmDSuqgVUWG2UQ/J6ArjP5sdn2koq4YV1Q1bi7fYg9Cu5bUPmW5q8CgWBvTPBemZp90dUD0wb3Q2ICqW9AezPPSw5176Nin6pUuGqsimzPKaEG732BoeE20hhvEVxKDlyt+HEA5th7lfrzDV0V+uk/oWiRXm4ly0IBpxYGc4bi5PZ672hTgVfynZD53Cot7vmZS8cAR7Rd+QtSrZR+2FZnJbIiIofMFDv8VqEimGRLhm+cllZdXuSQXHfJt6yE=
  matrix:
    - RACKET_VERSION=6.6
    - RACKET_VERSION=6.9
    - RACKET_VERSION=6.10.1
    - RACKET_VERSION=6.11
    - RACKET_VERSION=6.12
    - RACKET_VERSION=HEAD

matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
  fast_finish: true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install
  - wget -q -O bin/cplex ${CPLEX_URL}
  - chmod +x bin/cplex

script:
  - raco test
  - time raco make test/all-rosette-tests.rkt
  - raco test test/all-rosette-tests.rkt
  - time raco make test/all-sdsl-tests.rkt
  - raco test test/all-sdsl-tests.rkt
  - raco test test/cplex/solve.rkt
