language: java
sudo: false

env:
  global:
    - RACKET_DIR=~/racket
  matrix:
    - RACKET_VERSION=6.1
    - RACKET_VERSION=6.1.1
    - RACKET_VERSION=6.2
    - RACKET_VERSION=6.3
    - RACKET_VERSION=6.4
    - RACKET_VERSION=6.5
    - RACKET_VERSION=6.6
    - RACKET_VERSION=6.7
    - RACKET_VERSION=6.8
    - RACKET_VERSION=6.9
    - RACKET_VERSION=6.10
    - RACKET_VERSION=6.10.1
    - RACKET_VERSION=HEAD
    - RACKET_VERSION=RELEASE

matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
    - env: RACKET_VERSION=RELEASE

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install

script:
  - raco test
  - time raco make test/all-rosette-tests.rkt
  - raco test test/all-rosette-tests.rkt
  - time raco make test/all-sdsl-tests.rkt
  - raco test test/all-sdsl-tests.rkt

