language: c
sudo: false

env:
  global:
    - RACKET_DIR=~/racket
    - CVC4_URL="http://cvc4.cs.stanford.edu/downloads/builds/x86_64-linux-opt/cvc4-1.5-x86_64-linux-opt"
    - BOOLECTOR_URL="http://fmv.jku.at/boolector/boolector-2.4.1-with-lingeling-bbc.tar.bz2"
    # - YICES_URL="http://yices.csl.sri.com/releases/2.6.0/yices-2.6.0-x86_64-pc-linux-gnu-static-gmp.tar.gz"
  matrix:
    - RACKET_VERSION=6.9
    - RACKET_VERSION=7.0
    - RACKET_VERSION=HEAD
    - RACKET_VERSION=7.0 ALL_SOLVERS=1

matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
  fast_finish: true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}"
  - if [ "$ALL_SOLVERS" == "1" ]; then
      mkdir bin &&
      wget $CVC4_URL -nv -O bin/cvc4 &&
      chmod +x bin/cvc4 &&
      wget $BOOLECTOR_URL -nv -O boolector.tar.bz2 &&
      tar xjf boolector.tar.bz2 &&
      make -C boolector-* &&
      cp boolector-*/boolector/bin/boolector bin/ &&
      rm -rf boolector*;
      # wget $YICES_URL -nv -O yices.tar.gz &&
      # tar xzf yices.tar.gz &&
      # cp yices-*/bin/yices-smt2 bin/ &&
      # rm -rf yices-*;
    fi


install:
  - raco pkg install

script:
  - time raco make test/all-rosette-tests.rkt
  - raco test test/all-rosette-tests.rkt
  - time raco make test/all-sdsl-tests.rkt
  - raco test test/all-sdsl-tests.rkt
