language: c
sudo: false

env:
  global:
    - RACKET_DIR=~/racket
    - secure: "gfyx+39n6/7Osr1NFXxBT708vbNwrR6eeyZ0sn8ZhklkVPAB5xIvecx3kVtnuKx/SNfR6XN4EGefhcfbyxgXVUteiNhCsfQBBP4FPdfZO1rA/qTzEnZrdEoBgjmv8Ln7eM4Z9oXLb32jvXsjYBRs8VoAdH73SNp7Z3BItLJ7e/dla8ISpNu5SAY+dONHqqu4GL4aaSgXNY2tz2B+gvw3KjqD309tIBGd7AgYjRwloqFyUxh3IpqCccc+ef2eqVt9UgDVy3LZkeguAVnX/dv2sHWXmPwBZ7KFo0pOsryxTWdjBU8m2wPMf+SezQV/FU7wuZqDGrLCef8vQNg/K4Weta+rmxw+3fMuhD0o8kCWS9rgYQOIEGtzasgQWq18OHVkW0xzfu3CmgPNsxPj6jLcfCLQPT93MMvl6veeoGqMKodiygdKo8kfcLUBwIZG2WKL9TPBVdJ5e24LfD3fmrhrlV8oiXJUYiDwGzJ8/1MPKvLdDRRsgXBdvAou4CKNkUPObB13FURzHxjHpFzCxTilA7gLJYlUboZdjiWnlKh/w5tmahwV5NTdUuwvkiYRb7btVHhXAXxvxiADrhX316RN5r1CPeg2W0P07Fq23OHYutGA8VR9AblA2NBtHYJ2sFBLHo0T/J0q/BkqggoZBrfpmseinBepPbDpBMgZc+shm7w="
  matrix:
    - RACKET_VERSION=6.6
    - RACKET_VERSION=6.9
    - RACKET_VERSION=6.10.1
    - RACKET_VERSION=6.11
    - RACKET_VERSION=6.12
    - RACKET_VERSION=HEAD

matrix:
  allow_failures:
    - env: RACKET_VERSION=HEAD
  fast_finish: true

before_install:
  - git clone https://github.com/greghendershott/travis-racket.git
  - cat travis-racket/install-racket.sh | bash # pipe to bash not sh!
  - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
  - raco pkg install
  - wget -q -O bin/cplex $CPLEX_URL
  - chmod +x bin/cplex

script:
  - raco test
  - time raco make test/all-rosette-tests.rkt
  - raco test test/all-rosette-tests.rkt
  - time raco make test/all-sdsl-tests.rkt
  - raco test test/all-sdsl-tests.rkt
  - raco test test/cplex/solve.rkt
